name: Build and Push

on:
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Login
      run: |
        docker login -u ${{secrets.DOCKER_USERNAME}} \
        -p ${{secrets.DOCKER_TOKEN}}

    - name: Build
      run: |
        docker build . -t \
        ${{secrets.DOCKER_USERNAME}}/${{secrets.DOCKER_TAG}}:${{secrets.TAG_NAME}}

    - name: Push
      run: |
        docker push \
        ${{secrets.DOCKER_USERNAME}}/${{secrets.DOCKER_TAG}}:${{secrets.TAG_NAME}}